

export enum Env{
    TELEGRAM_BOT_TOKEN='TELEGRAM_BOT_TOKEN',
    OPEN_AI_API_KEY='OPEN_AI_API_KEY',
    GOOGLE_API_CLIENT_ID='GOOGLE_API_CLIENT_ID',
    GOOGLE_API_CLIENT_SECRET='GOOGLE_API_CLIENT_SECRET',
    TAVILY_API_KEY='TAVILY_API_KEY',
    PORT='PORT'
}